# Generated by Django 6.0.4 on 2026-04-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_video_url_lesson_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='url',
            new_name='extra_url',
        ),
    ]
